# Generated by Django 3.0.7 on 2020-06-28 18:32

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20200628_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=job.models.Job.uploadedfile),
        ),
    ]
